var webpack = require('webpack');
var path = require('path');
var ROOT_PATH = path.resolve(__dirname);

module.exports = {  
  //entry define the entry point of the application
  entry: [
    path.resolve(ROOT_PATH, 'src/index'),
  ],
  //out put define the output file generated by Webpack
  output: {
    path: path.resolve(ROOT_PATH, 'public', 'build'),
    publicPath: '/build/',
    filename: 'bundle.js'
  },
  module: {
    //The module.loaders section allows to specify transformations on specific files.
    loaders: [
      {
        test: /\.(jsx|js)$/,
        exclude: /node_modules/,
        loader: ['babel'],
        query: {
          presets: ['es2015', 'react']
        }
      },
      {
        test: /\.scss$/,
        loaders: ['style', 'css', 'sass']
      },
      { 
        test: /\.less?$/, 
        loaders: ['style', 'css', 'less']   
      },
      { 
        test: /\.(png|jpg)$/, 
        loader: 'url-loader',
        include: path.resolve(ROOT_PATH, 'src/style/asset') 
      },
      {
        test: /\.json$/,
        loaders: ['json']
      }
    ]
  },
  resolve: {
    extensions: ['', '.js', '.jsx'],
    alias: {
      component: path.resolve(ROOT_PATH, 'src/component'),
      style: path.resolve(ROOT_PATH, 'src/style'),
      asset: path.resolve(ROOT_PATH, 'src/style/asset'),
      store: path.resolve(ROOT_PATH, 'src/redux'),
    }
  },
  devServer: {
    contentBase: path.resolve(ROOT_PATH, 'public'),
    historyApiFallback: true,
    hot: true,
    inline: true,
    progress: true,
    host: require('./config.json').host,
    port: require('./config.json').port
  },
  //use plugins to declare and configure all the optimizations plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin()
  ]
}; 